### ISSUE TITLE
cannot find module 'bulk-require'

### ISSUE THREAD

**Issue by kevzettler** [contra/rtc-everywhere#9]
This has been my experience so far: 

```
Kevins-MBP:client kevzettler$ npm install rtc-everywhere
rtc-everywhere@0.0.4 node_modules/rtc-everywhere
├── add-event-listener@0.0.1
├── new-operator@1.0.3
├── crel@2.1.8
├── detect-browser@1.3.1
├── domready@1.0.8
├── uuid@2.0.1
├── ortc-adapter@0.1.6 (sdp-transform@1.5.3)
├── lodash.merge@3.3.2 (lodash.istypedarray@3.0.3, lodash.isarguments@3.0.5, lodash.isarray@3.0.4, lodash.keys@3.1.2, lodash._arrayeach@3.0.0, lodash.keysin@3.0.8, lodash._arraycopy@3.0.0, lodash._getnative@3.9.1, lodash.isplainobject@3.2.0, lodash.toplainobject@3.0.0, lodash._createassigner@3.1.1)
├── volume-meter@2.0.1 (raf@3.1.0)
└── browserify-optional@1.0.0 (ast-types@0.7.8, browser-resolve@1.11.1, ast-transform@0.0.0)

Kevins-MBP:client kevzettler$ node
> var rtc = require('rtc-everywhere');
Error: Cannot find module 'bulk-require'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/kevzettler/plebland/client/node_modules/rtc-everywhere/lib/findPlatform.js:3:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
>
```

**Comment by yocontra** [comment]
@kevzettler Node support is in-progress (and pretty simple to add), but kind of on hold until the `wrtc` module authors get it together. It doesn't work on any current release of node AFAIK

**Comment by yocontra** [comment]
As for the issue with bulk-require not being installed which causes an error on require, just fixed and published as 0.0.5

**Comment by yocontra** [comment]
I went ahead and added node support (on master) - if you can get the `wrtc` module to install then it should work just fine. I haven't been able to get it to build, so I haven't been able to test it but theoretically it should work - If you have any issues let me know.

**Comment by kevzettler** [comment]
@contra sorry I encountered this in a webpack browser build. I used the node cli to demonstrate it failed on require. Thanks for the quick fix!. 

I'm using the `wrtc` module seperately and I suggest using their provided `Dockerfile` https://github.com/js-platform/node-webrtc/blob/develop/Dockerfile to install all the weird dependencies

**Comment by cmalven** [comment]
For what it's worth, I just installed `0.0.5` and I'm still getting errors when using `var rtc = require('rtc-everywhere')();` via Webpack:

```
WARNING in ./~/rtc-everywhere/~/bulk-require/index.js
Critical dependencies:
8:36-43 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/rtc-everywhere/~/bulk-require/index.js 8:36-43

WARNING in ./~/rtc-everywhere/~/bulk-require/package.json
Module parse failed: /Users/cmalven/Code/sticks-and-stones/node_modules/rtc-everywhere/node_modules/bulk-require/package.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "name": "bulk-require",
|   "version": "0.2.1",
|   "description": "require a whole directory of trees in bulk",
 @ ./~/rtc-everywhere/~/bulk-require ^\.\/.*$

WARNING in ./~/rtc-everywhere/~/bulk-require/~/glob/~/minimatch/minimatch.js
Critical dependencies:
6:5-12 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/rtc-everywhere/~/bulk-require/~/glob/~/minimatch/minimatch.js 6:5-12

WARNING in ./~/rtc-everywhere/~/bulk-require/LICENSE
Module parse failed: /Users/cmalven/Code/sticks-and-stones/node_modules/rtc-everywhere/node_modules/bulk-require/LICENSE Line 1: Unexpected identifier
You may need an appropriate loader to handle this file type.
| This software is released under the MIT license:
|
| Permission is hereby granted, free of charge, to any person obtaining a copy of
 @ ./~/rtc-everywhere/~/bulk-require ^\.\/.*$

WARNING in ./~/rtc-everywhere/~/bulk-require/readme.markdown
Module parse failed: /Users/cmalven/Code/sticks-and-stones/node_modules/rtc-everywhere/node_modules/bulk-require/readme.markdown Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| # bulk-require
|
| require a whole directory of trees in bulk
 @ ./~/rtc-everywhere/~/bulk-require ^\.\/.*$

WARNING in ./~/rtc-everywhere/~/bulk-require/~/glob/~/minimatch/package.json
Module parse failed: /Users/cmalven/Code/sticks-and-stones/node_modules/rtc-everywhere/node_modules/bulk-require/node_modules/glob/node_modules/minimatch/package.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "author": {
|     "name": "Isaac Z. Schlueter",
|     "email": "i@izs.me",
 @ ./~/rtc-everywhere/~/bulk-require/~/glob/~/minimatch ^\.\/.*$

WARNING in ./~/rtc-everywhere/~/bulk-require/~/glob/~/minimatch/README.md
Module parse failed: /Users/cmalven/Code/sticks-and-stones/node_modules/rtc-everywhere/node_modules/bulk-require/node_modules/glob/node_modules/minimatch/README.md Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| # minimatch
|
| A minimal matching utility.
 @ ./~/rtc-everywhere/~/bulk-require/~/glob/~/minimatch ^\.\/.*$

WARNING in ./~/rtc-everywhere/~/bulk-require/~/glob/~/minimatch/LICENSE
Module parse failed: /Users/cmalven/Code/sticks-and-stones/node_modules/rtc-everywhere/node_modules/bulk-require/node_modules/glob/node_modules/minimatch/LICENSE Line 1: Unexpected number
You may need an appropriate loader to handle this file type.
| Copyright 2009, 2010, 2011 Isaac Z. Schlueter.
| All rights reserved.
|
 @ ./~/rtc-everywhere/~/bulk-require/~/glob/~/minimatch ^\.\/.*$

ERROR in ./~/rtc-everywhere/~/bulk-require/~/glob/glob.js
Module not found: Error: Cannot resolve module 'fs' in /Users/cmalven/Code/sticks-and-stones/node_modules/rtc-everywhere/node_modules/bulk-require/node_modules/glob
 @ ./~/rtc-everywhere/~/bulk-require/~/glob/glob.js 39:9-22

ERROR in ./~/rtc-everywhere/~/bulk-require/example/args.js
Module not found: Error: Cannot resolve module 'level' in /Users/cmalven/Code/sticks-and-stones/node_modules/rtc-everywhere/node_modules/bulk-require/example
 @ ./~/rtc-everywhere/~/bulk-require/example/args.js 1:12-28

ERROR in ./~/rtc-everywhere/~/bulk-require/test/args.js
Module not found: Error: Cannot resolve module 'tape' in /Users/cmalven/Code/sticks-and-stones/node_modules/rtc-everywhere/node_modules/bulk-require/test
 @ ./~/rtc-everywhere/~/bulk-require/test/args.js 1:11-26

ERROR in ./~/rtc-everywhere/~/bulk-require/test/glob.js
Module not found: Error: Cannot resolve module 'tape' in /Users/cmalven/Code/sticks-and-stones/node_modules/rtc-everywhere/node_modules/bulk-require/test
 @ ./~/rtc-everywhere/~/bulk-require/test/glob.js 2:11-26

ERROR in ./~/rtc-everywhere/~/bulk-require/test/glob/glob.js
Module not found: Error: Cannot resolve directory '..' in /Users/cmalven/Code/sticks-and-stones/node_modules/rtc-everywhere/node_modules/bulk-require/test/glob
 @ ./~/rtc-everywhere/~/bulk-require/test/glob/glob.js 1:11-25

ERROR in ./~/rtc-everywhere/~/bulk-require/~/glob/~/minimatch/test/basic.js
Module not found: Error: Cannot resolve module 'tap' in /Users/cmalven/Code/sticks-and-stones/node_modules/rtc-everywhere/node_modules/bulk-require/node_modules/glob/node_modules/minimatch/test
 @ ./~/rtc-everywhere/~/bulk-require/~/glob/~/minimatch/test/basic.js 6:10-24

ERROR in ./~/rtc-everywhere/~/bulk-require/~/glob/~/minimatch/test/brace-expand.js
Module not found: Error: Cannot resolve module 'tap' in /Users/cmalven/Code/sticks-and-stones/node_modules/rtc-everywhere/node_modules/bulk-require/node_modules/glob/node_modules/minimatch/test
 @ ./~/rtc-everywhere/~/bulk-require/~/glob/~/minimatch/test/brace-expand.js 1:10-24

ERROR in ./~/rtc-everywhere/~/bulk-require/~/glob/~/minimatch/test/caching.js
Module not found: Error: Cannot resolve module 'tap' in /Users/cmalven/Code/sticks-and-stones/node_modules/rtc-everywhere/node_modules/bulk-require/node_modules/glob/node_modules/minimatch/test
 @ ./~/rtc-everywhere/~/bulk-require/~/glob/~/minimatch/test/caching.js 2:10-24

ERROR in ./~/rtc-everywhere/~/bulk-require/~/glob/~/minimatch/test/extglob-ending-with-state-char.js
Module not found: Error: Cannot resolve module 'tap' in /Users/cmalven/Code/sticks-and-stones/node_modules/rtc-everywhere/node_modules/bulk-require/node_modules/glob/node_modules/minimatch/test
 @ ./~/rtc-everywhere/~/bulk-require/~/glob/~/minimatch/test/extglob-ending-with-state-char.js 1:11-25

ERROR in ./~/rtc-everywhere/~/bulk-require/~/glob/~/minimatch/test/defaults.js
Module not found: Error: Cannot resolve module 'tap' in /Users/cmalven/Code/sticks-and-stones/node_modules/rtc-everywhere/node_modules/bulk-require/node_modules/glob/node_modules/minimatch/test
 @ ./~/rtc-everywhere/~/bulk-require/~/glob/~/minimatch/test/defaults.js 6:10-24
```

**Comment by yocontra** [comment]
@cmalven Can you open a new issue about webpack support? It's unrelated to this ticket.
